---
driver:
  name: vagrant
  network:
    -  ["private_network", {ip: "192.168.33.32" }]

provisioner:
  name: chef_zero
  # You may wish to disable always updating cookbooks in CI or other testing environments.
  # For example:
  #   always_update_cookbooks: <%= !ENV['CI'] %>
  always_update_cookbooks: true
  product_version: 14
  client_rb:
    chef_license: accept
    

verifier:
  name: inspec

platforms:
  - name: ubuntu-14.04
    driver:
      box: ubuntu/trusty64
  #- name: centos-7

suites:
  - name: default
    run_list:
      - recipe[myck2::default]
    verifier:
      inspec_tests:
        - test/integration/default
    attributes:
